# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3cyEeW7qoDfhgn-asatytx0tJnm2tWU
"""

#task2

inp = open("/content/input2.txt","r")
out = open("/content/output2.txt","w")

n, m = map(int, inp.readline().split())
tasks = []
for i in range(n):
    start, end = map(int, inp.readline().split())
    tasks.append((start, end))

tasks.sort(key=lambda x: x[1])
completion_times = [0] * m
completed_tasks = 0

for task in tasks:
    for i in range(m):
        if completion_times[i] <= task[0]:
            completion_times[i] = task[1]
            completed_tasks += 1
            break


out.write(str(completed_tasks))