# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3cyEeW7qoDfhgn-asatytx0tJnm2tWU
"""

#task1

inp = open("/content/input1.txt","r")
out = open("/content/output1.txt","w")
n_tasks = int(inp.readline())
tasks = []
for i in range(n_tasks):
     start, end = map(int, inp.readline().split())
     tasks.append((start, end))

tasks.sort(key=lambda x: x[1])
selected_tasks = []
end_time = -1
for task in tasks:
    if task[0] >= end_time:
        selected_tasks.append(task)
        end_time = task[1]


out.write(str(len(selected_tasks)) + '\n')
for task in selected_tasks:
     out.write(f'{task[0]} {task[1]}\n')